language: cpp

sudo: false

cache:
    apt: true
    directories:
        - $HOME/cmake

install:
    - if [ ! -f $HOME/cmake/bin/cmake ]; then
          if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
            wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
            && tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz
            && mkdir -p $HOME/cmake
            && cp -fR cmake-3.3.2-Linux-x86_64/* $HOME/cmake
            ;
          else
            brew update
            && brew unlink cmake
            ;
          fi
        fi

addons:
    apt:
        packages:
            - gcc-5
            - g++-5
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise

matrix:
    include:
        - env: CXX_COMPILER=gcc
          os: linux

before_script:
    - if [ "${CXX_COMPILER}" = "clang" ]; then
        export CXX=clang-3.7;
      elif [ "${CXX_COMPILER}" = "gcc" ]; then
        export CXX=g++-5;
      fi

script:
    - mkdir -p build
      && cd build
      && $HOME/cmake/bin/cmake ..
      && make
