language: cpp

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-i386.tar.gz
        && tar -xzf cmake-3.3.2-Linux-i386.tar.gz
        && sudo cp -fR cmake-3.3.2-Linux-i386/* /usr
        ;
      else
        brew update
        && brew unlink cmake
        ;
      fi

matrix:
    include:
        - env: CLANG_VERSION=3.7 CPP=14 LIBCXX=On
          os: linux
          addons: &clang37
          apt:
              packages:
                  - clang-3.7
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise

        - env: GCC_VERSION=5.0 CPP=14 LIBCXX=Off
          os: linux
          addons: &gcc5
          apt:
              packages:
                  - g++-5
                  - gcc-5
              sources:
                  - ubuntu-toolchain-t-test

script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
